version: "3.4"
name: async-report

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d/
    ports:
      - 3000:3000
      - 81:81
      - 82:82
      - 15672:15672
      - 9001:9001
      - 9000:9000
      - 9090:9090
      - 3001:3001
      - 16686:16686
    depends_on:
      - web
      - api
      - notification-hub
      - report-worker
      - rabbitmq
      - minio
      - jaeger
      - prometheus
      - loki
    networks:
      - report

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    container_name: web
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./web:/app
      - /app/node_modules
    networks:
      - report

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.25
    environment:
      RABBITMQ_CONNECTIONSTRING: amqp://mc:mc2@rabbitmq:5672/main
      RABBITMQ_CONNECTMAXATTEMPTS: 3
      RABBITMQ_QOS: 5
      RABBITMQ_REPORT_EXCHANGE: report
      RABBITMQ_REPORT_QUEUE: report
      LOKI__ENDPOINT: http://loki
      LOKI__PORT: 3100
    depends_on:
      - rabbitmq
      - minio
    networks:
      - report

  notification-hub:
    build:
      context: ./notification-hub
      dockerfile: Dockerfile
    container_name: hub
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.25
    environment:
      RABBITMQ_CONNECTIONSTRING: amqp://mc:mc2@rabbitmq:5672/main
      RABBITMQ_CONNECTMAXATTEMPTS: 3
      RABBITMQ_QOS: 5
      RABBITMQ_NOTIFICATION_EXCHANGE: notification
      RABBITMQ_NOTIFICATION_QUEUE: notification
      LOKI__ENDPOINT: http://loki
      LOKI__PORT: 3100
    depends_on:
      - rabbitmq
      - minio
    networks:
      - report

  report-worker:
    build:
      context: ./report-worker
      dockerfile: Dockerfile
    container_name: worker
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.25
    environment:
      RABBITMQ_CONNECTIONSTRING: amqp://mc:mc2@rabbitmq:5672/main
      RABBITMQ_CONNECTMAXATTEMPTS: 3
      RABBITMQ_QOS: 5
      RABBITMQ_REPORT_EXCHANGE: report
      RABBITMQ_REPORT_QUEUE: report
      RABBITMQ_NOTIFICATION_EXCHANGE: notification
      RABBITMQ_NOTIFICATION_QUEUE: notification
      MINIO_ENDPOINT: localhost:9000
      MINIO_ENDPOINT_PROXY: proxy:9000
      MINIO_ACCESSKEY: Zu8VgBoZMU2xcmOEeS70
      MINIO_SECRETKEY: xvnjYyFQyFs44iuUagi4kTHiOGvlK1PiX64LiwOy
      MINIO_BUCKET_FILES: files
      LOKI__ENDPOINT: http://loki
      LOKI__PORT: 3100
    depends_on:
      - rabbitmq
      - minio
    networks:
      - report

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST=main
      - RABBITMQ_DEFAULT_USER=mc
      - RABBITMQ_DEFAULT_PASS=mc2
    networks:
      - report

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: Zu8VgBoZMU2xcmOEeS70
      MINIO_SECRET_KEY: xvnjYyFQyFs44iuUagi4kTHiOGvlK1PiX64LiwOy
    networks:
      - report

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    volumes:
      - jaeger:/badger
    networks:
      - report

  prometheus:
    image: prom/prometheus:v2.24.1
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - report

  grafana:
    image: grafana/grafana:7.2.1
    container_name: grafana
    volumes:
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - report

  loki:
    image: grafana/loki:master
    container_name: base-loki
    volumes:
      - ./loki/config/loki-config.yaml:/etc/loki/loki-config.yaml
      - ./loki/data:/data/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - report

volumes:
  jaeger:

networks:
  report:
    external: true
    driver: bridge
