version: "3.4"

services:
  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d/
    ports:
      - 3000:3000
      - 81:81
      - 82:82
      - 15672:15672
      - 9001:9001
      - 9000:9000
    depends_on:
      - web
      - api
      - notification-hub
      - worker
      - rabbitmq
      - minio
    networks:
      - report

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./web:/app
      - /app/node_modules
    networks:
      - report

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      RABBITMQ_CONNECTIONSTRING: amqp://mc:mc2@rabbitmq:5672/main
      RABBITMQ_CONNECTMAXATTEMPTS: 3
      RABBITMQ_QOS: 5
      RABBITMQ_REPORT_EXCHANGE: report
      RABBITMQ_REPORT_QUEUE: report
    depends_on:
      - rabbitmq
      - minio
    networks:
      - report

  notification-hub:
    build:
      context: ./notification-hub
      dockerfile: Dockerfile
    environment:
      RABBITMQ_CONNECTIONSTRING: amqp://mc:mc2@rabbitmq:5672/main
      RABBITMQ_CONNECTMAXATTEMPTS: 3
      RABBITMQ_QOS: 5
      RABBITMQ_NOTIFICATION_EXCHANGE: notification
      RABBITMQ_NOTIFICATION_QUEUE: notification
    depends_on:
      - rabbitmq
      - minio
    networks:
      - report

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      RABBITMQ_CONNECTIONSTRING: amqp://mc:mc2@rabbitmq:5672/main
      RABBITMQ_CONNECTMAXATTEMPTS: 3
      RABBITMQ_QOS: 5
      RABBITMQ_REPORT_EXCHANGE: report
      RABBITMQ_REPORT_QUEUE: report
      RABBITMQ_NOTIFICATION_EXCHANGE: notification
      RABBITMQ_NOTIFICATION_QUEUE: notification
      MINIO_ENDPOINT: localhost:9000
      MINIO_ENDPOINT_PROXY: proxy:9000
      MINIO_ACCESSKEY: Zu8VgBoZMU2xcmOEeS70
      MINIO_SECRETKEY: xvnjYyFQyFs44iuUagi4kTHiOGvlK1PiX64LiwOy
      MINIO_BUCKET_FILES: files
    depends_on:
      - rabbitmq
      - minio
    networks:
      - report

  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbitmq
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST=main
      - RABBITMQ_DEFAULT_USER=mc
      - RABBITMQ_DEFAULT_PASS=mc2
    networks:
      - report

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: Zu8VgBoZMU2xcmOEeS70
      MINIO_SECRET_KEY: xvnjYyFQyFs44iuUagi4kTHiOGvlK1PiX64LiwOy
    networks:
      - report

networks:
  report:
    driver: bridge
