version: '3.4'

services:
  notificationhub:
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      RABBITMQ_CONNECTIONSTRING: amqp://mc:mc2@rabbitmq:5672/main
      RABBITMQ_CONNECTMAXATTEMPTS: 3
      RABBITMQ_QOS: 5
      RABBITMQ_NOTIFICATION_EXCHANGE: notification
      RABBITMQ_NOTIFICATION_QUEUE: notification
    ports:
      - 82:80    
    networks:
      - report

networks:
  report:
    external: true