apiVersion: 1

datasources:
  - name: Prometheus - Metrics
    editable: true
    type: prometheus
    access: proxy
    url: http://prometheus:9090/
    isDefault: true

  - name: Loki - Logs
    editable: false
    type: loki
    access: proxy
    url: http://loki:3100/
    isDefault: false
