{
 "title": "Asp.Net Core - Geral",
 "tags": [
  "prometheus-net",
  "net",
  "prometheus",
  ".net",
  ".net core"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instances",
    "label": "instances",
    "query": "label_values(http_requests_received_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Duração Solicitações HTTP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Garbage Collector",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dotnet_collection_count_total[$interval])",
     "legendFormat": "Generation-{{generation}}"
    }
   ]
  },
  {
   "title": "Número total de Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_num_threads", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Total de Memória Alocada",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Número de Handles",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_handles", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Solicitações em Andamento",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "http_requests_in_progress", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Conjunto de Trabalho",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_working_set_bytes /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}