version: '3.4'

services:
  reportapi:
    image: ${DOCKER_REGISTRY-}reportapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 81:80
    environment:
      RABBITMQ_CONNECTIONSTRING: amqp://mc:mc2@rabbitmq:5672/main
      RABBITMQ_CONNECTMAXATTEMPTS: 3
      RABBITMQ_QOS: 5
      RABBITMQ_REPORT_EXCHANGE: report
      RABBITMQ_REPORT_QUEUE: report
    networks:
      - report

networks:
  report:
    external: true